### ISSUE TITLE
FileNotFoundError when installing with pip

### ISSUE THREAD

**Issue by cbenhagen** [wyattoday/python-turboactivate#9]
```
$ pip install --upgrade turboactivate
Collecting turboactivate
  Using cached https://files.pythonhosted.org/packages/21/3c/ee8914c000d26f6b57428ed6f6a58ae763e51b95f5d562020bf73670d37f/turboactivate-4.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n0/1b5b642541s_q7rc6v0jhp_80000gn/T/pip-install-wl0wc1jv/turboactivate/setup.py", line 24, in <module>
        long_description=open("README.md").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by wlcx** [comment]
+1. This fails because `README.md` is not included in the package tarball from pypi.
4.0.1 on pypi appears to be sourced from https://github.com/develersrl/python-turboactivate, which has several major API differences to 4.0.2!

**Comment by wyattoday** [comment]
Yeah, there was a problem with the tool we used to upload files to pip. We'll figure it out closer to the 4.1 release. In the meantime just checkout the latest branch from github.

**Comment by wyattoday** [comment]
Also referenced here: https://wyday.com/forum/viewtopic.php?f=3&t=28271

**Comment by wyattoday** [comment]
Fixed. Thanks for reporting (and for your patience).
